name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REPO: main
      AWS_ACCOUNT_ID: 305870070165

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::305870070165:role/GithubActionsRole
        aws-region: eu-west-2

    # Login to Private ECR - 
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com

    # Build and push Identity Lambda
    - name: Build and Push Identity Lambda
      run: |
        cd src/identity
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPO:identity .
        docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPO:identity

    # Terraform deployment
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0

    - name: Terraform Init
      run: |
        terraform init -backend-config="bucket=configs-305870070165"
      working-directory: ./infra

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./infra

    - name: Terraform Plan
      env:
        TF_VAR_mongodb_uri: ${{ secrets.MONGODB_URI }}
      run: terraform plan
      working-directory: ./infra

    - name: Terraform Apply
      env:
        TF_VAR_mongodb_uri: ${{ secrets.MONGODB_URI }}
      run: terraform apply -auto-approve
      working-directory: ./infra