name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::305870070165:role/GithubActionsRole
        aws-region: eu-west-2

    # Login to Public ECR
    - name: Login to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c2n6x7m0

    # Build and push Identity Lambda
    - name: Build and Push Identity Lambda
      run: |
        cd src/identity
        docker build -t public.ecr.aws/c2n6x7m0/email-services:identity-latest .
        docker push public.ecr.aws/c2n6x7m0/email-services:identity-latest

    # # Build and push Email Lambda
    # - name: Build Email Lambda Docker image
    #   run: |
    #     cd src/email
    #     docker build -t public.ecr.aws/c2n6x7m0/email-services:email-${{ github.sha }} .
    #     docker tag public.ecr.aws/c2n6x7m0/email-services:email-${{ github.sha }} public.ecr.aws/c2n6x7m0/email-services:email-latest

    # - name: Push Email Lambda Docker image
    #   run: |
    #     docker push public.ecr.aws/c2n6x7m0/email-services:email-${{ github.sha }}
    #     docker push public.ecr.aws/c2n6x7m0/email-services:email-latest

    # Terraform deployment
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0

    - name: Terraform Init
      run: |
        terraform init -backend-config="bucket=configs-305870070165"
      working-directory: ./infra

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./infra

    - name: Terraform Plan
      env:
        TF_VAR_identity_image_tag: identity-latest
        TF_VAR_email_image_tag: email-latest
        TF_VAR_mongodb_uri: ${{ secrets.MONGODB_URI }}
      run: terraform plan
      working-directory: ./infra

    - name: Terraform Apply
      env:
        TF_VAR_identity_image_tag: identity-latest
        TF_VAR_email_image_tag: email-latest
        TF_VAR_mongodb_uri: ${{ secrets.MONGODB_URI }}
      run: terraform apply -auto-approve
      working-directory: ./infra